target-version = "py312"

[format]
quote-style = "single"
docstring-code-format = false

[lint]
extend-select = ["C4", "E4", "E7", "E9", "F"]
ignore = [
    "C408", "C409", "C410",
    "E701", "E722", "E731",
    "I001",
    "UP017", "UP018",
]

[lint.per-file-ignores]
"healthcheck.py" = ["S110"]
"shasum_tests.py" = ["RUF059", "SIM117", "UP012"]
"**/management/commands/*.py" = ["N999"]
"**/migrations/0*.py" = ["I001", "RUF012"]

[lint.isort]
known-first-party = ["common", "sync", "tubesync"]

[per-file-target-version]
"shasum.py" = "py310"
