# Generated by Django 3.1.4 on 2020-12-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='Hostname or IP address of the media server', max_length=200, verbose_name='host')),
                ('port', models.PositiveIntegerField(help_text='Port number of the media server', verbose_name='port')),
                ('https', models.BooleanField(default=False, help_text='Connect to the media server over HTTPS', verbose_name='https')),
                ('options', models.TextField(blank=True, help_text='JSON encoded options for the media server', null=True, verbose_name='options')),
                ('valid', models.BooleanField(default=False, help_text='Media server details are valid and passed testing', verbose_name='valid')),
            ],
            options={
                'verbose_name': 'Media Server',
                'verbose_name_plural': 'Media Servers',
                'unique_together': {('host', 'port')},
            },
        ),
    ]
