# Generated by Django 3.1.3 on 2020-11-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_auto_20201126_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='key',
            field=models.CharField(db_index=True, help_text='Source key, such as exact YouTube channel name or playlist ID', max_length=100, unique=True, verbose_name='key'),
        ),
    ]
