# Generated by Django 3.1.4 on 2020-12-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_mediaserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaserver',
            name='host',
            field=models.CharField(db_index=True, help_text='Hostname or IP address of the media server', max_length=200, verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='mediaserver',
            name='port',
            field=models.PositiveIntegerField(db_index=True, help_text='Port number of the media server', verbose_name='port'),
        ),
    ]
