# Generated by Django 3.1.3 on 2020-11-28 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_auto_20201127_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='url',
        ),
    ]
