# Generated by Django 3.1.4 on 2020-12-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_auto_20201211_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaserver',
            name='server_type',
            field=models.CharField(choices=[('p', 'Plex')], db_index=True, default='p', help_text='Server type', max_length=1, verbose_name='server type'),
        ),
    ]
