# Generated by Django 3.1.4 on 2020-12-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_auto_20201219_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='write_nfo',
            field=models.BooleanField(default=False, help_text='Write an NFO file with the media, these may be detected and used by some media servers', verbose_name='write nfo'),
        ),
    ]
