# Generated by Django 3.1.4 on 2020-12-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_remove_mediaserver_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaserver',
            name='https',
        ),
        migrations.AddField(
            model_name='mediaserver',
            name='use_https',
            field=models.BooleanField(default=True, help_text='Connect to the media server over HTTPS', verbose_name='use https'),
        ),
        migrations.AddField(
            model_name='mediaserver',
            name='verify_https',
            field=models.BooleanField(default=False, help_text='If connecting over HTTPS, verify the SSL certificate is valid', verbose_name='verify https'),
        ),
    ]
