# Generated by Django 3.2.11 on 2022-02-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0010_auto_20210924_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='write_json',
            field=models.BooleanField(
                default=False, help_text='Write a JSON file with the media info, these may be detected and used by some media servers', verbose_name='write json'),
        ),
    ]
