# Generated by Django 3.2.12 on 2022-04-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0011_auto_20220201_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='downloaded_format',
            field=models.CharField(blank=True, help_text='Video format (resolution) of the downloaded media', max_length=30, null=True, verbose_name='downloaded format'),
        ),
    ]
