# Generated by Django 3.1.4 on 2020-12-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0011_auto_20201206_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='index_schedule',
            field=models.IntegerField(db_index=True, default=21600, help_text='Schedule of when to index the source for new media', verbose_name='index schedule'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_acodec',
            field=models.CharField(choices=[('MP4A', 'MP4A'), ('OPUS', 'OPUS')], db_index=True, default='OPUS', help_text='Source audio codec, desired audio encoding format to download', max_length=8, verbose_name='source audio codec'),
        ),
    ]
