# Generated by Django 3.1.4 on 2020-12-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0013_auto_20201207_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='has_errors',
            field=models.BooleanField(default=False, help_text='Source has errors', verbose_name='has errors'),
        ),
    ]
