# Generated by Django 3.2.18 on 2023-02-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0015_auto_20230213_0603'),
        ('sync', '0015_auto_20230214_2052'),
    ]

    operations = [
    ]
