# Generated by Django 3.1.4 on 2020-12-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0017_auto_20201208_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='can_download',
            field=models.BooleanField(db_index=True, default=False, help_text='Media has a matching format and can be downloaded', verbose_name='can download'),
        ),
    ]
