# Generated by pac

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0018_source_subtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='delete_removed_media',
            field=models.BooleanField(default=False, help_text='Delete media that is no longer on this playlist', verbose_name='delete removed media'),
        ),
    ]
