# Generated by Django 3.1.4 on 2020-12-11 03:06

import django.core.files.storage
from django.db import migrations, models
import sync.models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0019_auto_20201209_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='download_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time the download completed', null=True, verbose_name='download date'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(blank=True, help_text='Media file', max_length=200, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/meeb/Repos/github.com/meeb/tubesync/tubesync/downloads'), upload_to=sync.models.get_media_file_path, verbose_name='media file'),
        ),
        migrations.AlterUniqueTogether(
            name='media',
            unique_together={('source', 'key')},
        ),
    ]
