# Generated by Django 3.2.23 on 2024-01-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0020_auto_20231024_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='download_streams',
            field=models.BooleanField(default=False, help_text='Download live stream media from this source', verbose_name='download streams'),
        ),
        migrations.AddField(
            model_name='source',
            name='index_streams',
            field=models.BooleanField(default=False, help_text='Index live stream media from this source', verbose_name='index streams'),
        ),
    ]
