# Generated by Django 3.1.4 on 2020-12-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0020_auto_20201211_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='downloaded_height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in pixels of the downloaded media', null=True, verbose_name='downloaded height'),
        ),
        migrations.AddField(
            model_name='media',
            name='downloaded_width',
            field=models.PositiveIntegerField(blank=True, help_text='Width in pixels of the downloaded media', null=True, verbose_name='downloaded width'),
        ),
    ]
