# Generated by pac

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0020_auto_20231024_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='delete_files_on_disk',
            field=models.BooleanField(default=False, help_text='Delete files on disk when they are removed from TubeSync', verbose_name='delete files on disk'),
        ),
    ]