# Generated by Django 3.2.25 on 2025-01-29 06:14

from django.db import migrations
import sync.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0026_alter_source_sub_langs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='sponsorblock_categories',
            field=sync.fields.CommaSepChoiceField(default='all', max_length=128, help_text='Select the sponsorblocks you want to enforce', possible_choices=[('sponsor', 'Sponsor'), ('intro', 'Intermission/Intro Animation'), ('outro', 'Endcards/Credits'), ('selfpromo', 'Unpaid/Self Promotion'), ('preview', 'Preview/Recap'), ('filler', 'Filler Tangent'), ('interaction', 'Interaction Reminder'), ('music_offtopic', 'Non-Music Section')], verbose_name=''),
        ),
    ]
