# Generated by Django 3.2.25 on 2025-01-31 07:10

from django.db import migrations
import sync.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0027_alter_source_sponsorblock_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='sponsorblock_categories',
            field=sync.fields.CommaSepChoiceField(default='all', help_text='Select the sponsorblocks you want to enforce', max_length=128, possible_choices=[('sponsor', 'Sponsor'), ('intro', 'Intermission/Intro Animation'), ('outro', 'Endcards/Credits'), ('selfpromo', 'Unpaid/Self Promotion'), ('preview', 'Preview/Recap'), ('filler', 'Filler Tangent'), ('interaction', 'Interaction Reminder'), ('music_offtopic', 'Non-Music Section')], verbose_name=''),
        ),
    ]
