# Generated by Django 5.1.9 on 2025-05-10 06:18

import common.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0032_metadata_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaserver',
            name='options',
            field=models.JSONField(encoder=common.json.JSONEncoder, help_text='Options for the media server', null=True, verbose_name='options'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_acodec',
            field=models.CharField(choices=[('OPUS', 'OPUS'), ('MP4A', 'MP4A')], db_index=True, default='OPUS', help_text='Source audio codec, desired audio encoding format to download', max_length=8, verbose_name='source audio codec'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_vcodec',
            field=models.CharField(choices=[('AV1', 'AV1'), ('VP9', 'VP9'), ('AVC1', 'AVC1 (H.264)')], db_index=True, default='VP9', help_text='Source video codec, desired video encoding format to download (ignored if "resolution" is audio only)', max_length=8, verbose_name='source video codec'),
        ),
    ]
