# Generated by Django 5.2.1 on 2025-05-28 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sync', '0033_alter_mediaserver_options_alter_source_source_acodec_and_more'),
        #('sync', '0034_source_target_schedule_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('media', 'site', 'key')},
        ),
        migrations.AddField(
            model_name='metadata',
            name='source',
            field=models.ForeignKey(
                blank=True,
                help_text='Source from which the video was retrieved',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='videos',
                related_query_name='video',
                to='sync.source',
            ),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='media',
            field=models.OneToOneField(
                blank=True,
                help_text='Media the metadata belongs to',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='new_metadata',
                to='sync.media',
            ),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='retrieved',
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text='Date and time the metadata was retrieved',
                verbose_name='retrieved',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('media', 'site', 'key'), ('source', 'site', 'key')},
        ),
    ]

