# Generated by Django 5.2.7 on 2025-11-12 08:12
import sync.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sync', '0035_alter_metadata_unique_together_metadata_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='sponsorblock_categories',
            field=sync.fields.CommaSepChoiceField(
                all_choice='all',
                all_label='(All Categories)',
                allow_all=True,
                default='all',
                help_text='Select the SponsorBlock categories that you wish to be removed from downloaded videos.',
                max_length=128,
                possible_choices=[
                    ('sponsor', 'Sponsor'),
                    ('intro', 'Intermission/Intro Animation'),
                    ('outro', 'Endcards/Credits'),
                    ('selfpromo', 'Unpaid/Self Promotion'),
                    ('preview', 'Preview/Recap'),
                    ('filler', 'Filler Tangent'),
                    ('interaction', 'Interaction Reminder'),
                    ('music_offtopic', 'Non-Music Section'),
                    ('hook', 'Hook/Greetings'),
                ],
                verbose_name='removed categories',
            ),         
        ),
    ]
