# Generated by Django 6.0.8 on 2026-09-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sync', '0037_alter_source_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='prefer_original_audio',
            field=models.BooleanField(
                default=True,
                help_text='Some videos offer more than one audio language: the language the video was recorded in ("original"), plus dubbed tracks, one of which the site marks as the "default". Prefer the original-language track when enabled, or the default track when disabled. This has no effect on videos with only one audio language, or when audio and video are downloaded as separate streams',
                verbose_name='prefer original audio',
            ),
        ),
    ]
