# Generated by Django 6.0.4 on 2026-04-18 01:42

import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0037_alter_source_fallback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codec',
            fields=[
                ('uuid', models.UUIDField(
                    default=uuid.uuid4, editable=False, help_text='UUID of the codec', primary_key=True, serialize=False, verbose_name='uuid'),
                ),
                ('asset_type', models.CharField(
                    choices=[
                        ('thumbnail', 'Thumbnail'),
                        ('audio', 'Audio'),
                        ('video', 'Video'),
                        ('subtitle', 'Subtitle'),
                    ],
                    db_index=True, help_text='The type of asset this codec is used for', max_length=16, verbose_name='asset type'),
                ),
                ('codec', models.CharField(
                    db_index=True, help_text='The codec extension', max_length=16, verbose_name='codec'),
                ),
                ('description', models.CharField(
                    help_text='A text description / label for this codec', max_length=128, verbose_name='description'),
                ),
            ],
            options={
                'verbose_name': 'Codec',
                'verbose_name_plural': 'Codecs',
                'unique_together': {('asset_type', 'codec')},
            },
        ),
    ]

