# Generated by Django 5.2.11 on 2026-09-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0037_alter_source_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='prefer_audio_track',
            field=models.CharField(
                choices=[
                    ('original', 'Original audio (recorded language)'),
                    ('default', "Publisher's default audio (often an auto-dub)"),
                ],
                db_index=True,
                default='original',
                help_text=(
                    'Which audio track to download when the source publishes more than one. '
                    '"Original audio" is the track in the language the video was actually '
                    'recorded in. "Publisher\'s default audio" is whichever track the uploader '
                    'set as the default for viewers, which for many channels is an automatic '
                    'dubbed translation. This setting has no effect when a video only offers a '
                    'single audio track.'
                ),
                max_length=8,
                verbose_name='prefer audio track',
            ),
        ),
    ]
