# Generated by Django 6.0.8 on 2026-09-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0038_source_audio_track'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'get_latest_by': ('-retrieved', '-created'), 'verbose_name': 'Metadata about Media', 'verbose_name_plural': 'Metadata about Media'},
        ),
        migrations.AlterModelOptions(
            name='metadataformat',
            options={'ordering': ('site', 'key', 'number'), 'verbose_name': 'Format from Media Metadata', 'verbose_name_plural': 'Formats from Media Metadata'},
        ),
    ]
