# Generated by Django 6.0.8 on 2026-09-08 14:19
# Fork: re-parented onto the fork's migration chain (upstream numbered this 0038,
# which collides with the fork-only 0038_directdownloadjob). The redundant
# fork-only 0039_source_prefer_audio_track is reconciled in
# 0042_transfer_prefer_audio_track.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0040_directdownloadjob_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='audio_track',
            field=models.CharField(choices=[('o', 'Original audio (recorded language)'), ('d', "Publisher's default audio (often an auto-dub)")], db_index=True, default='o', help_text='Which audio track to download when the source publishes more than one. "Original audio" is the track in the language the video was actually recorded in. "Publisher\'s default audio" is whichever track the uploader set as the default for viewers, which for many channels is an automatic dubbed translation. This setting has no effect when a video only offers a single audio track.', max_length=1, verbose_name='audio track'),
        ),
    ]
