# Generated by Django 3.1.3 on 2020-12-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_remove_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='thumb_height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Height (Y) of the thumbnail', null=True, verbose_name='thumb height'),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumb_width',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Width (X) of the thumbnail', null=True, verbose_name='thumb width'),
        ),
    ]
