# Generated by Django 3.1.3 on 2020-12-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0008_auto_20201205_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_vcodec',
            field=models.CharField(choices=[('AVC1', 'AVC1 (H.264)'), ('VP9', 'VP9')], db_index=True, default='VP9', help_text='Source video codec, desired video encoding format to download (ignored if "resolution" is audio only)', max_length=8, verbose_name='source video codec'),
        ),
    ]
