# Generated by Django 3.1.4 on 2020-12-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0009_auto_20201205_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='directory',
            field=models.CharField(db_index=True, help_text='Directory name to save the media into', max_length=100, unique=True, verbose_name='directory'),
        ),
        migrations.AlterField(
            model_name='source',
            name='fallback',
            field=models.CharField(choices=[('f', 'Fail, do not download any media'), ('s', 'Get next best SD media or codec instead'), ('h', 'Get next best HD media or codec instead')], db_index=True, default='f', help_text='What do do when media in your source resolution and codecs is not available', max_length=1, verbose_name='fallback'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(db_index=True, help_text='Friendly name for the source, used locally in TubeSync only', max_length=100, unique=True, verbose_name='name'),
        ),
    ]
