# Generated by Django 3.1.4 on 2020-12-09 08:57

from django.db import migrations, models
import sync.models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0018_media_can_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_file',
            field=models.FileField(blank=True, help_text='Media file', max_length=200, null=True, upload_to=sync.models.get_media_file_path, verbose_name='media file'),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumb',
            field=models.ImageField(blank=True, height_field='thumb_height', help_text='Thumbnail', max_length=200, null=True, upload_to=sync.models.get_media_thumb_path, verbose_name='thumb', width_field='thumb_width'),
        ),
    ]
