#!/command/with-contenv bash

set -e
cd /app

DB_HIGH_SIZE='500000'
DB_LOW_SIZE='100000'

DIR="${XDG_STATE_HOME:-/config/state}/hat"
DATABASE="${DIR}/syslog.db"

mkdir -p "${DIR}"
chown -R app:app "${DIR}"
chmod 0700 "${DIR}"

exec s6-setuidgid app \
    hat-syslog-server --log-level 'INFO' \
        --db-high-size "${DB_HIGH_SIZE}" --db-low-size "${DB_LOW_SIZE}" \
        --db-enable-archive --db-path "${DATABASE}"
