#!/command/with-contenv bash

cd /

https="${TUBESYNC_POT_HTTPS:+https}"
ip_address="${TUBESYNC_POT_IPADDR:-${POTSERVER_PORT_4416_TCP_ADDR}}"
: "${TUBESYNC_POT_PORT:=${POTSERVER_PORT_4416_TCP_PORT}}"
port="${TUBESYNC_POT_PORT:+:}${TUBESYNC_POT_PORT}"

if [ -n "${ip_address}" ]
then
    YT_POT_BGUTIL_BASE_URL="${https:-http}://${ip_address}${port}"
    export YT_POT_BGUTIL_BASE_URL
fi

exec /usr/bin/openresty -c /etc/nginx/nginx.conf -e stderr
