#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

cd /app || exit

exec s6-setuidgid app \
    /usr/local/bin/gunicorn -c /app/tubesync/gunicorn.py --capture-output tubesync.wsgi:application
