#!/command/with-contenv bash

# Change runtime user UID and GID
PUID="${PUID:-911}"
PUID="${PUID:-911}"
groupmod -o -g "$PGID" app
usermod -o -u "$PUID" app

# Reset permissions
chown -R app:app /run/app
chmod -R 0700 /run/app
chown -R app:app /config
chmod -R 0755 /config
chown -R root:app /app
chmod -R 0750 /app
chmod 0755 /app/*.py /app/*.sh
find /app -mindepth 2 -type f -execdir chmod 640 '{}' +
chown -R app:app /app/common/static
chown -R app:app /app/static

# Optionally reset the download dir permissions
if [ "${TUBESYNC_RESET_DOWNLOAD_DIR:=True}" == "True" ]
then
    export TUBESYNC_RESET_DOWNLOAD_DIR
    echo "TUBESYNC_RESET_DOWNLOAD_DIR=True, Resetting /downloads directory permissions"
    chown -R app:app /downloads
    chmod -R 0755 /downloads
fi

# Run migrations
exec s6-setuidgid app \
    /usr/bin/python3 /app/manage.py migrate
