#!/command/with-contenv bash

# Change runtime user UID and GID
groupmod -o -g "${PGID:=911}" app
usermod -o -u "${PUID:=911}" app

# Ensure existence and reset permissions
mkdir -v -p /run/app
chown -R app:app /run/app
chmod -R 0700 /run/app

# Ensure /config directories exist
mkdir -v -p /config/{cache,media,state,tasks,tubesync}

# Reset permissions
chown -R app:app /config
chmod -R 0755 /config
