# Generated by Django 5.2.3 on 2025-06-30 07:11

import common.json
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=190)),
                ('task_id', models.CharField(db_index=True, max_length=40)),
                ('task_params', models.JSONField(default=dict, encoder=common.json.JSONEncoder)),
                ('verbose_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('queue', models.CharField(blank=True, db_index=True, max_length=190, null=True)),
                ('attempts', models.IntegerField(db_index=True, default=0)),
                ('failed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('repeat', models.BigIntegerField(default=0)),
                ('repeat_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]


