# Generated by Django 5.2.4 on 2025-07-03 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='elapsed',
            field=models.FloatField(default=float),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='scheduled_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='attempts',
            field=models.IntegerField(db_index=True, default=int),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='repeat',
            field=models.BigIntegerField(default=int),
        ),
    ]

