# Generated by Django 5.2.4 on 2025-07-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_taskhistory_elapsed_taskhistory_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='remove_duplicates',
            field=models.BooleanField(default=bool),
        ),
    ]

