# Generated by Django 5.2.4 on 2025-07-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_taskhistory_remove_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='task_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]

