name: No Response

# `issues`.`closed`, `issues`.`labeled`, `issue_comment`.`created`,
# and `scheduled` event types are required for this Action
# to work properly.
on:
  workflow_dispatch:
  issues:
    types: [closed, labeled]
  issue_comment:
    types: [created]
  schedule:
    # A recurring 40, 30, 70, 50, 40, 70 minute gap pattern
    - cron: '7 1,6,11,16,21 * * *'
    - cron: '17 4,9,14,19 * * *'
    - cron: '27 0,5,10,15,20,23 * * *'
    - cron: '37 1,3,6,8,11,13,16,18,21 * * *'
    - cron: '47 2,7,12,17,22 * * *'

jobs:
  noResponse:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: tcely/no-response@tcely-issues
        with:
          token: ${{ github.token }}
          # auto close issues with no response from author for N days
          daysUntilClose: 30
          # label to use to track when a response is required (once a response is made, this label will be auto removed)
          # if the label doesn't exist, it will be auto-created
          responseRequiredLabel: "waiting-on-author"
          # once the responseRequiredLabel is removed, this one will be added for tracking on maintainers' side
          ##optionalFollowupLabel: "status: waiting for maintainer's response"
          # this comment will be posted when closing the issue
          closeComment: >
            The issue has been closed due to no response from the author.
            Responses, from the original author of the issue,
            should automatically re-open the issue.
